import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    //Check {inter.className}

    <html lang="en" className='dark bg-black'>
      <body className="bg-white dark:bg-black text-black text-base dark:text-white font-inter">{children}</body>
    </html>

  )
}
